import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"; // Header ichida dark mode bo'ladi

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-gray-900`}>
        <Header />
        <div className="mt-16 text-black dark:text-white">{children}</div>
      </body>
    </html>
  );
}
